import type { Role, WorkflowType } from "../../types";
import type { ActionCode, ApprovalTypeForTransition } from "./workflow-types";

/**
 * ============================================================================
 * Stage E-1 데모 전용 설정 — 명시적 전이 정의표
 * ============================================================================
 * 이 표가 "합법적인 전이"의 유일한 출처다. 런타임의 어떤 함수도 order/order+1/
 * order-1 연산으로 다음·이전 단계를 계산하지 않는다 — 오직 이 배열을
 * (workflowType, actionCode, fromStepKey) 키로 조회할 뿐이다. order는
 * workflowSteps(mock-data.ts)의 표시/정렬 용도로만 쓰인다(WorkflowProgress.tsx).
 *
 * 75개 행 = 정방향(STEP_ADVANCED) 36 + 교정 반환(STEP_RETURNED) 36 +
 * 출하 완료(SHIPMENT_COMPLETED) 3(워크플로당 1개). product_intake는 어떤 시드
 * 데이터에서도 currentWorkflowStepKey로 등장하지 않는 도달 불가능 단계이므로
 * (신규 접수는 항상 intake_inspection에서 시작 — submit-intake.ts 참고)
 * 전이 그래프에서 의도적으로 제외한다. shipment_completed는 종료 단계이며
 * SHIPMENT_COMPLETED 전용 액션으로만 도달한다(일반 정방향 진행으로는 도달할
 * 수 없다).
 *
 * allowedRoles/requiresAssignedEngineer는 각 행의 fromStepKey가 속한
 * step-category.ts 분류(TECHNICAL/BUSINESS/PARTS_SHIPMENT)로부터 산출한
 * 값이며(SUPER_ADMIN/ADMIN은 항상 포함), 교정 반환은 분류와 무관하게 항상
 * SUPER_ADMIN/ADMIN만 허용한다. 출하 완료는 SUPER_ADMIN/ADMIN/
 * INVENTORY_MANAGER만 허용한다(SALES/AS_ENGINEER 제외).
 *
 * MATCHER의 "교산 회신 대기"가 두 번(order 4 waiting_kyosan_reply, order 8
 * waiting_kyosan_reply_followup) 등장하는 것은 서로 다른 fromStepKey/toStepKey를
 * 가진 완전히 독립된 행으로 표현된다(행 id 참고) — 라벨이 같다고 같은
 * 전이로 취급하지 않는다.
 * ============================================================================
 */

export type TransitionDirection = "FORWARD" | "RETURN" | "TERMINAL";

export type TransitionDefinition = {
  id: string;
  workflowType: WorkflowType;
  actionCode: ActionCode;
  fromStepKey: string;
  toStepKey: string;
  toStatus: import("../../types").RepairStatus;
  direction: TransitionDirection;
  allowedRoles: readonly Role[];
  requiresAssignedEngineer: boolean;
  requiresReason: boolean;
  requiredApprovalType: ApprovalTypeForTransition | null;
};

export const TRANSITION_DEFINITIONS: readonly TransitionDefinition[] = [
  { id: "wf-MATCHER-ADV-intake_inspection", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "intake_inspection", toStepKey: "kyosan_contact_report_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-kyosan_contact_report_sent", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "kyosan_contact_report_sent", toStepKey: "intake_inspection", toStatus: "WAITING_INTAKE_INSPECTION", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-kyosan_contact_report_sent", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "kyosan_contact_report_sent", toStepKey: "waiting_kyosan_reply", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-waiting_kyosan_reply", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_reply", toStepKey: "kyosan_contact_report_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-waiting_kyosan_reply", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_reply", toStepKey: "kyosan_instruction_confirmed", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-kyosan_instruction_confirmed", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "kyosan_instruction_confirmed", toStepKey: "waiting_kyosan_reply", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-kyosan_instruction_confirmed", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "kyosan_instruction_confirmed", toStepKey: "instructed_parts_replacement_or_check", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-instructed_parts_replacement_or_check", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "instructed_parts_replacement_or_check", toStepKey: "kyosan_instruction_confirmed", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-instructed_parts_replacement_or_check", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "instructed_parts_replacement_or_check", toStepKey: "kyosan_followup_report_sent", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-kyosan_followup_report_sent", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "kyosan_followup_report_sent", toStepKey: "instructed_parts_replacement_or_check", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-kyosan_followup_report_sent", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "kyosan_followup_report_sent", toStepKey: "waiting_kyosan_reply_followup", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-waiting_kyosan_reply_followup", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_reply_followup", toStepKey: "kyosan_followup_report_sent", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-waiting_kyosan_reply_followup", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_reply_followup", toStepKey: "quote_drafted_per_kyosan_instruction", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-quote_drafted_per_kyosan_instruction", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "quote_drafted_per_kyosan_instruction", toStepKey: "waiting_kyosan_reply_followup", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-quote_drafted_per_kyosan_instruction", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "quote_drafted_per_kyosan_instruction", toStepKey: "customer_quote_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-customer_quote_sent", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "customer_quote_sent", toStepKey: "quote_drafted_per_kyosan_instruction", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-customer_quote_sent", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "customer_quote_sent", toStepKey: "waiting_po", toStatus: "WAITING_PO", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-waiting_po", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "waiting_po", toStepKey: "customer_quote_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-waiting_po", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_po", toStepKey: "po_received", toStatus: "WAITING_PO", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-po_received", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "po_received", toStepKey: "waiting_po", toStatus: "WAITING_PO", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-po_received", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "po_received", toStepKey: "parts_supply", toStatus: "WAITING_PARTS_SUPPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-parts_supply", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "parts_supply", toStepKey: "po_received", toStatus: "WAITING_PO", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-parts_supply", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "parts_supply", toStepKey: "repair_in_progress", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-repair_in_progress", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "repair_in_progress", toStepKey: "parts_supply", toStatus: "WAITING_PARTS_SUPPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-repair_in_progress", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "repair_in_progress", toStepKey: "power_on_test", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-power_on_test", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "power_on_test", toStepKey: "repair_in_progress", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-power_on_test", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "power_on_test", toStepKey: "waiting_kyosan_shipment_approval", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: "REPAIR_INSPECTION" },
  { id: "wf-MATCHER-RET-waiting_kyosan_shipment_approval", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_shipment_approval", toStepKey: "power_on_test", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-waiting_kyosan_shipment_approval", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_shipment_approval", toStepKey: "shipment_approved", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-shipment_approved", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "shipment_approved", toStepKey: "waiting_kyosan_shipment_approval", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-ADV-shipment_approved", workflowType: "MATCHER", actionCode: "STEP_ADVANCED", fromStepKey: "shipment_approved", toStepKey: "waiting_shipment", toStatus: "WAITING_SHIPMENT", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-MATCHER-RET-waiting_shipment", workflowType: "MATCHER", actionCode: "STEP_RETURNED", fromStepKey: "waiting_shipment", toStepKey: "shipment_approved", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-MATCHER-SHIP", workflowType: "MATCHER", actionCode: "SHIPMENT_COMPLETED", fromStepKey: "waiting_shipment", toStepKey: "shipment_completed", toStatus: "SHIPMENT_COMPLETED", direction: "TERMINAL", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: "FINAL_SHIPMENT" },

  { id: "wf-PAID_GENERATOR-ADV-intake_inspection", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "intake_inspection", toStepKey: "parts_supply", toStatus: "WAITING_PARTS_SUPPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-parts_supply", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "parts_supply", toStepKey: "intake_inspection", toStatus: "WAITING_INTAKE_INSPECTION", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-parts_supply", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "parts_supply", toStepKey: "repair_or_defective_parts_replacement", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-repair_or_defective_parts_replacement", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "repair_or_defective_parts_replacement", toStepKey: "parts_supply", toStatus: "WAITING_PARTS_SUPPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-repair_or_defective_parts_replacement", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "repair_or_defective_parts_replacement", toStepKey: "power_on_test", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-power_on_test", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "power_on_test", toStepKey: "repair_or_defective_parts_replacement", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-power_on_test", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "power_on_test", toStepKey: "kyosan_contact_report_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-kyosan_contact_report_sent", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "kyosan_contact_report_sent", toStepKey: "power_on_test", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-kyosan_contact_report_sent", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "kyosan_contact_report_sent", toStepKey: "waiting_kyosan_reply", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-waiting_kyosan_reply", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_reply", toStepKey: "kyosan_contact_report_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-waiting_kyosan_reply", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_reply", toStepKey: "quote_drafted_per_kyosan_instruction", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-quote_drafted_per_kyosan_instruction", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "quote_drafted_per_kyosan_instruction", toStepKey: "waiting_kyosan_reply", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-quote_drafted_per_kyosan_instruction", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "quote_drafted_per_kyosan_instruction", toStepKey: "customer_quote_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-customer_quote_sent", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "customer_quote_sent", toStepKey: "quote_drafted_per_kyosan_instruction", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-customer_quote_sent", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "customer_quote_sent", toStepKey: "waiting_po", toStatus: "WAITING_PO", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-waiting_po", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "waiting_po", toStepKey: "customer_quote_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-waiting_po", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_po", toStepKey: "po_received", toStatus: "WAITING_PO", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-po_received", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "po_received", toStepKey: "waiting_po", toStatus: "WAITING_PO", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-po_received", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "po_received", toStepKey: "final_power_on_test_decision", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-final_power_on_test_decision", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "final_power_on_test_decision", toStepKey: "po_received", toStatus: "WAITING_PO", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-final_power_on_test_decision", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "final_power_on_test_decision", toStepKey: "final_power_on_test", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-final_power_on_test", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "final_power_on_test", toStepKey: "final_power_on_test_decision", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-final_power_on_test", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "final_power_on_test", toStepKey: "waiting_kyosan_shipment_approval", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: "REPAIR_INSPECTION" },
  { id: "wf-PAID_GENERATOR-RET-waiting_kyosan_shipment_approval", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_shipment_approval", toStepKey: "final_power_on_test", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-ADV-waiting_kyosan_shipment_approval", workflowType: "PAID_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_shipment_approval", toStepKey: "shipment_approved", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-RET-shipment_approved", workflowType: "PAID_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "shipment_approved", toStepKey: "waiting_kyosan_shipment_approval", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-PAID_GENERATOR-SHIP", workflowType: "PAID_GENERATOR", actionCode: "SHIPMENT_COMPLETED", fromStepKey: "shipment_approved", toStepKey: "shipment_completed", toStatus: "SHIPMENT_COMPLETED", direction: "TERMINAL", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: "FINAL_SHIPMENT" },

  { id: "wf-WARRANTY_GENERATOR-ADV-intake_inspection", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "intake_inspection", toStepKey: "parts_supply", toStatus: "WAITING_PARTS_SUPPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-RET-parts_supply", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "parts_supply", toStepKey: "intake_inspection", toStatus: "WAITING_INTAKE_INSPECTION", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-ADV-parts_supply", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "parts_supply", toStepKey: "kyosan_contact_report_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-RET-kyosan_contact_report_sent", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "kyosan_contact_report_sent", toStepKey: "parts_supply", toStatus: "WAITING_PARTS_SUPPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-ADV-kyosan_contact_report_sent", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "kyosan_contact_report_sent", toStepKey: "waiting_kyosan_reply", toStatus: "WAITING_KYOSAN_REPLY", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-RET-waiting_kyosan_reply", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_reply", toStepKey: "kyosan_contact_report_sent", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-ADV-waiting_kyosan_reply", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_reply", toStepKey: "repair_or_defective_parts_replacement", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "SALES"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-RET-repair_or_defective_parts_replacement", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "repair_or_defective_parts_replacement", toStepKey: "waiting_kyosan_reply", toStatus: "WAITING_KYOSAN_REPLY", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-ADV-repair_or_defective_parts_replacement", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "repair_or_defective_parts_replacement", toStepKey: "power_on_test", toStatus: "IN_REPAIR", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-RET-power_on_test", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "power_on_test", toStepKey: "repair_or_defective_parts_replacement", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-ADV-power_on_test", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "power_on_test", toStepKey: "waiting_kyosan_shipment_approval", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "AS_ENGINEER"], requiresAssignedEngineer: true, requiresReason: false, requiredApprovalType: "REPAIR_INSPECTION" },
  { id: "wf-WARRANTY_GENERATOR-RET-waiting_kyosan_shipment_approval", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "waiting_kyosan_shipment_approval", toStepKey: "power_on_test", toStatus: "IN_REPAIR", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-ADV-waiting_kyosan_shipment_approval", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_ADVANCED", fromStepKey: "waiting_kyosan_shipment_approval", toStepKey: "shipment_approved", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "FORWARD", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: false, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-RET-shipment_approved", workflowType: "WARRANTY_GENERATOR", actionCode: "STEP_RETURNED", fromStepKey: "shipment_approved", toStepKey: "waiting_kyosan_shipment_approval", toStatus: "WAITING_SHIPMENT_APPROVAL", direction: "RETURN", allowedRoles: ["SUPER_ADMIN", "ADMIN"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: null },
  { id: "wf-WARRANTY_GENERATOR-SHIP", workflowType: "WARRANTY_GENERATOR", actionCode: "SHIPMENT_COMPLETED", fromStepKey: "shipment_approved", toStepKey: "shipment_completed", toStatus: "SHIPMENT_COMPLETED", direction: "TERMINAL", allowedRoles: ["SUPER_ADMIN", "ADMIN", "INVENTORY_MANAGER"], requiresAssignedEngineer: false, requiresReason: true, requiredApprovalType: "FINAL_SHIPMENT" },
];

/** (workflowType, actionCode, fromStepKey)로 단일 전이를 조회한다. 없으면 undefined. */
export function findTransitionDefinition(
  workflowType: WorkflowType,
  actionCode: ActionCode,
  fromStepKey: string
): TransitionDefinition | undefined {
  return TRANSITION_DEFINITIONS.find(
    (t) => t.workflowType === workflowType && t.actionCode === actionCode && t.fromStepKey === fromStepKey
  );
}

/** 현재 단계에서 가능한 모든 명시적 전이(방향 무관)를 반환한다. */
export function listTransitionsFrom(workflowType: WorkflowType, fromStepKey: string): TransitionDefinition[] {
  return TRANSITION_DEFINITIONS.filter((t) => t.workflowType === workflowType && t.fromStepKey === fromStepKey);
}
