import type {
  AttachmentMetadata,
  Customer,
  EndUser,
  Product,
  RepairCase,
  User,
  WorkflowStep,
  WorkHistory,
} from "./types";

// 아래 데이터는 전부 가상의 데모 데이터이며, 실제 DSS 직원/고객사/장비/연락처와
// 무관하다. 이메일은 예약된 예시 도메인(example.test)만 사용한다.

export const mockUsers: User[] = [
  {
    id: "u-001",
    name: "김도윤",
    email: "kim.doyoon@example.test",
    role: "SUPER_ADMIN",
    approvalStatus: "APPROVED",
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "u-002",
    name: "이서연",
    email: "lee.seoyeon@example.test",
    role: "ADMIN",
    approvalStatus: "APPROVED",
    createdAt: "2026-01-06T09:00:00.000Z",
  },
  {
    id: "u-003",
    name: "박지훈",
    email: "park.jihoon@example.test",
    role: "ADMIN",
    approvalStatus: "APPROVED",
    createdAt: "2026-01-07T09:00:00.000Z",
  },
  {
    id: "u-004",
    name: "최민서",
    email: "choi.minseo@example.test",
    role: "AS_ENGINEER",
    approvalStatus: "APPROVED",
    createdAt: "2026-02-10T09:00:00.000Z",
  },
  {
    id: "u-005",
    name: "정우진",
    email: "jeong.woojin@example.test",
    role: "AS_ENGINEER",
    approvalStatus: "APPROVED",
    createdAt: "2026-02-11T09:00:00.000Z",
  },
  {
    id: "u-006",
    name: "한소율",
    email: "han.soyul@example.test",
    role: "AS_ENGINEER",
    approvalStatus: "APPROVED",
    createdAt: "2026-02-12T09:00:00.000Z",
  },
  {
    id: "u-007",
    name: "오하늘",
    email: "oh.haneul@example.test",
    role: "AS_ENGINEER",
    approvalStatus: "PENDING",
    createdAt: "2026-07-28T09:00:00.000Z",
  },
  {
    id: "u-008",
    name: "강다인",
    email: "kang.dain@example.test",
    role: "SALES",
    approvalStatus: "APPROVED",
    createdAt: "2026-01-20T09:00:00.000Z",
  },
  {
    id: "u-009",
    name: "윤채영",
    email: "yoon.chaeyoung@example.test",
    role: "SALES",
    approvalStatus: "APPROVED",
    createdAt: "2026-01-21T09:00:00.000Z",
  },
  {
    id: "u-010",
    name: "임재현",
    email: "lim.jaehyun@example.test",
    role: "INVENTORY_MANAGER",
    approvalStatus: "APPROVED",
    createdAt: "2026-01-25T09:00:00.000Z",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c-001",
    name: "한빛전자(주)",
    contactName: "서지원",
    contactEmail: "contact@hanbit-demo.example.test",
    contactPhone: "02-000-1001",
  },
  {
    id: "c-002",
    name: "청람통신",
    contactName: "노현우",
    contactEmail: "contact@cheongram-demo.example.test",
    contactPhone: "032-000-1002",
  },
  {
    id: "c-003",
    name: "대성RF시스템",
    contactName: "배소민",
    contactEmail: "contact@daesungrf-demo.example.test",
    contactPhone: "042-000-1003",
  },
  {
    id: "c-004",
    name: "동해정밀",
    contactName: "구태윤",
    contactEmail: "contact@donghae-demo.example.test",
    contactPhone: "052-000-1004",
  },
  {
    id: "c-005",
    name: "은하계측기술",
    contactName: "표유나",
    contactEmail: "contact@eunha-demo.example.test",
    contactPhone: "02-000-1005",
  },
  {
    id: "c-006",
    name: "미래전자산업",
    contactName: "양지호",
    contactEmail: "contact@miraeelec-demo.example.test",
    contactPhone: "054-000-1006",
  },
  {
    id: "c-007",
    name: "온새미로테크",
    contactName: "설아름",
    contactEmail: "contact@onsaemiro-demo.example.test",
    contactPhone: "055-000-1007",
  },
];

export const mockEndUsers: EndUser[] = [
  {
    id: "eu-001",
    customerId: "c-001",
    name: "한빛전자 부산공장",
    contactName: "문성재",
    contactEmail: "busan@hanbit-demo.example.test",
  },
  {
    id: "eu-002",
    customerId: "c-001",
    name: "한빛전자 시험동",
    contactName: "홍은채",
    contactEmail: "lab@hanbit-demo.example.test",
  },
  {
    id: "eu-003",
    customerId: "c-002",
    name: "청람통신 인천지사",
    contactName: "장하람",
    contactEmail: "incheon@cheongram-demo.example.test",
  },
  {
    id: "eu-004",
    customerId: "c-003",
    name: "대성RF 대전연구소",
    contactName: "고은우",
    contactEmail: "daejeon@daesungrf-demo.example.test",
  },
  {
    id: "eu-005",
    customerId: "c-004",
    name: "동해정밀 울산공장",
    contactName: "심유진",
    contactEmail: "ulsan@donghae-demo.example.test",
  },
  {
    id: "eu-006",
    customerId: "c-005",
    name: "은하계측 본사실험실",
    contactName: "탁민준",
    contactEmail: "lab@eunha-demo.example.test",
  },
  {
    id: "eu-007",
    customerId: "c-006",
    name: "미래전자 구미공장",
    contactName: "위서인",
    contactEmail: "gumi@miraeelec-demo.example.test",
  },
  {
    id: "eu-008",
    customerId: "c-007",
    name: "온새미로 창원지사",
    contactName: "감도현",
    contactEmail: "changwon@onsaemiro-demo.example.test",
  },
  {
    id: "eu-009",
    customerId: "c-002",
    name: "청람통신 본사",
    contactName: "노현우",
    contactEmail: "hq@cheongram-demo.example.test",
  },
];

export const mockProducts: Product[] = [
  { id: "p-001", modelName: "TG-100", lotNumber: "DEMO-LN-1001", serialNumber: "DEMO-100234" },
  { id: "p-002", modelName: "TG-100", lotNumber: "DEMO-LN-1002", serialNumber: "DEMO-100587" },
  { id: "p-003", modelName: "TG-200", lotNumber: "DEMO-LN-2001", serialNumber: "DEMO-200114" },
  { id: "p-004", modelName: "TG-200", lotNumber: "DEMO-LN-2002", serialNumber: "DEMO-200456" },
  { id: "p-005", modelName: "TG-300", lotNumber: "DEMO-LN-3001", serialNumber: "DEMO-300021" },
  { id: "p-006", modelName: "TG-300", lotNumber: "DEMO-LN-3002", serialNumber: "DEMO-300099" },
  { id: "p-007", modelName: "TG-150", lotNumber: "DEMO-LN-1501", serialNumber: "DEMO-150077" },
  { id: "p-008", modelName: "TG-250", lotNumber: "DEMO-LN-2501", serialNumber: "DEMO-250033" },
  { id: "p-009", modelName: "TG-350", lotNumber: "DEMO-LN-3501", serialNumber: "DEMO-350061" },
];

// 아래는 각 워크플로 유형의 확정된 단계 순서를 그대로 옮긴 정적 참조 데이터다
// (PROJECT_REQUIREMENTS.md "워크플로 정의" 참조). 부품 조달 단계는 이번 단계
// 합의에 따라 "부품 수급"으로 표기한다. Matcher 워크플로는 "교산 회신 대기"가
// order 4와 8에 두 번 등장하며, 이 둘은 서로 다른 key
// (waiting_kyosan_reply / waiting_kyosan_reply_followup)를 가진다 — 한글
// 라벨이 같아도 개별 접수 건의 currentWorkflowStepKey는 둘을 구분한다.
export const workflowSteps: WorkflowStep[] = [
  // MATCHER
  { workflowType: "MATCHER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "MATCHER", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "MATCHER", order: 3, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "MATCHER", order: 4, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "MATCHER", order: 5, key: "kyosan_instruction_confirmed", label: "교산 지시사항 확인" },
  { workflowType: "MATCHER", order: 6, key: "instructed_parts_replacement_or_check", label: "지시된 부품 교체 또는 미비 점검 항목 확인" },
  { workflowType: "MATCHER", order: 7, key: "kyosan_followup_report_sent", label: "교산 후속 연락/보고서 발송" },
  { workflowType: "MATCHER", order: 8, key: "waiting_kyosan_reply_followup", label: "교산 회신 대기" },
  { workflowType: "MATCHER", order: 9, key: "quote_drafted_per_kyosan_instruction", label: "교산 지시에 따른 견적 작성" },
  { workflowType: "MATCHER", order: 10, key: "customer_quote_sent", label: "고객 견적 발송" },
  { workflowType: "MATCHER", order: 11, key: "waiting_po", label: "PO 대기" },
  { workflowType: "MATCHER", order: 12, key: "po_received", label: "PO 접수" },
  { workflowType: "MATCHER", order: 13, key: "parts_supply", label: "부품 수급" },
  { workflowType: "MATCHER", order: 14, key: "repair_in_progress", label: "수리" },
  { workflowType: "MATCHER", order: 15, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "MATCHER", order: 16, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "MATCHER", order: 17, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "MATCHER", order: 18, key: "waiting_shipment", label: "출하 대기" },
  { workflowType: "MATCHER", order: 19, key: "shipment_completed", label: "출하 완료" },

  // PAID_MATCHER — independent initial snapshot of legacy MATCHER.
  { workflowType: "PAID_MATCHER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "PAID_MATCHER", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "PAID_MATCHER", order: 3, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "PAID_MATCHER", order: 4, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "PAID_MATCHER", order: 5, key: "kyosan_instruction_confirmed", label: "교산 지시사항 확인" },
  { workflowType: "PAID_MATCHER", order: 6, key: "instructed_parts_replacement_or_check", label: "지시된 부품 교체 또는 미비 점검 항목 확인" },
  { workflowType: "PAID_MATCHER", order: 7, key: "kyosan_followup_report_sent", label: "교산 후속 연락/보고서 발송" },
  { workflowType: "PAID_MATCHER", order: 8, key: "waiting_kyosan_reply_followup", label: "교산 회신 대기" },
  { workflowType: "PAID_MATCHER", order: 9, key: "quote_drafted_per_kyosan_instruction", label: "교산 지시에 따른 견적 작성" },
  { workflowType: "PAID_MATCHER", order: 10, key: "customer_quote_sent", label: "고객 견적 발송" },
  { workflowType: "PAID_MATCHER", order: 11, key: "waiting_po", label: "PO 대기" },
  { workflowType: "PAID_MATCHER", order: 12, key: "po_received", label: "PO 접수" },
  { workflowType: "PAID_MATCHER", order: 13, key: "parts_supply", label: "부품 수급" },
  { workflowType: "PAID_MATCHER", order: 14, key: "repair_in_progress", label: "수리" },
  { workflowType: "PAID_MATCHER", order: 15, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "PAID_MATCHER", order: 16, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "PAID_MATCHER", order: 17, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "PAID_MATCHER", order: 18, key: "waiting_shipment", label: "출하 대기" },
  { workflowType: "PAID_MATCHER", order: 19, key: "shipment_completed", label: "출하 완료" },

  // WARRANTY_MATCHER — independent initial snapshot of legacy MATCHER.
  { workflowType: "WARRANTY_MATCHER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "WARRANTY_MATCHER", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "WARRANTY_MATCHER", order: 3, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "WARRANTY_MATCHER", order: 4, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "WARRANTY_MATCHER", order: 5, key: "kyosan_instruction_confirmed", label: "교산 지시사항 확인" },
  { workflowType: "WARRANTY_MATCHER", order: 6, key: "instructed_parts_replacement_or_check", label: "지시된 부품 교체 또는 미비 점검 항목 확인" },
  { workflowType: "WARRANTY_MATCHER", order: 7, key: "kyosan_followup_report_sent", label: "교산 후속 연락/보고서 발송" },
  { workflowType: "WARRANTY_MATCHER", order: 8, key: "waiting_kyosan_reply_followup", label: "교산 회신 대기" },
  { workflowType: "WARRANTY_MATCHER", order: 9, key: "quote_drafted_per_kyosan_instruction", label: "교산 지시에 따른 견적 작성" },
  { workflowType: "WARRANTY_MATCHER", order: 10, key: "customer_quote_sent", label: "고객 견적 발송" },
  { workflowType: "WARRANTY_MATCHER", order: 11, key: "waiting_po", label: "PO 대기" },
  { workflowType: "WARRANTY_MATCHER", order: 12, key: "po_received", label: "PO 접수" },
  { workflowType: "WARRANTY_MATCHER", order: 13, key: "parts_supply", label: "부품 수급" },
  { workflowType: "WARRANTY_MATCHER", order: 14, key: "repair_in_progress", label: "수리" },
  { workflowType: "WARRANTY_MATCHER", order: 15, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "WARRANTY_MATCHER", order: 16, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "WARRANTY_MATCHER", order: 17, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "WARRANTY_MATCHER", order: 18, key: "waiting_shipment", label: "출하 대기" },
  { workflowType: "WARRANTY_MATCHER", order: 19, key: "shipment_completed", label: "출하 완료" },

  // PAID_GENERATOR (유상 Generator)
  { workflowType: "PAID_GENERATOR", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "PAID_GENERATOR", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "PAID_GENERATOR", order: 3, key: "parts_supply", label: "부품 수급" },
  { workflowType: "PAID_GENERATOR", order: 4, key: "repair_or_defective_parts_replacement", label: "수리 또는 불량 부품 교체" },
  { workflowType: "PAID_GENERATOR", order: 5, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "PAID_GENERATOR", order: 6, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "PAID_GENERATOR", order: 7, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "PAID_GENERATOR", order: 8, key: "quote_drafted_per_kyosan_instruction", label: "교산 지시에 따른 견적 작성" },
  { workflowType: "PAID_GENERATOR", order: 9, key: "customer_quote_sent", label: "고객 견적 발송" },
  { workflowType: "PAID_GENERATOR", order: 10, key: "waiting_po", label: "PO 대기" },
  { workflowType: "PAID_GENERATOR", order: 11, key: "po_received", label: "PO 접수" },
  { workflowType: "PAID_GENERATOR", order: 12, key: "final_power_on_test_decision", label: "최종 전원 인가 테스트 필요 여부 판단" },
  { workflowType: "PAID_GENERATOR", order: 13, key: "final_power_on_test", label: "최종 전원 인가 테스트 수행" },
  { workflowType: "PAID_GENERATOR", order: 14, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "PAID_GENERATOR", order: 15, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "PAID_GENERATOR", order: 16, key: "shipment_completed", label: "출하 완료" },

  // WARRANTY_GENERATOR (무상(보증) Generator)
  { workflowType: "WARRANTY_GENERATOR", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "WARRANTY_GENERATOR", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "WARRANTY_GENERATOR", order: 3, key: "parts_supply", label: "부품 수급" },
  { workflowType: "WARRANTY_GENERATOR", order: 4, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "WARRANTY_GENERATOR", order: 5, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "WARRANTY_GENERATOR", order: 6, key: "repair_or_defective_parts_replacement", label: "수리 또는 불량 부품 교체" },
  { workflowType: "WARRANTY_GENERATOR", order: 7, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "WARRANTY_GENERATOR", order: 8, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "WARRANTY_GENERATOR", order: 9, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "WARRANTY_GENERATOR", order: 10, key: "shipment_completed", label: "출하 완료" },

  // PAID_TOTAL_CONTROLLER — independent initial snapshot of PAID_GENERATOR.
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 3, key: "parts_supply", label: "부품 수급" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 4, key: "repair_or_defective_parts_replacement", label: "수리 또는 불량 부품 교체" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 5, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 6, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 7, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 8, key: "quote_drafted_per_kyosan_instruction", label: "교산 지시에 따른 견적 작성" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 9, key: "customer_quote_sent", label: "고객 견적 발송" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 10, key: "waiting_po", label: "PO 대기" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 11, key: "po_received", label: "PO 접수" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 12, key: "final_power_on_test_decision", label: "최종 전원 인가 테스트 필요 여부 판단" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 13, key: "final_power_on_test", label: "최종 전원 인가 테스트 수행" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 14, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 15, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "PAID_TOTAL_CONTROLLER", order: 16, key: "shipment_completed", label: "출하 완료" },

  // WARRANTY_TOTAL_CONTROLLER — independent initial snapshot of WARRANTY_GENERATOR.
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 3, key: "parts_supply", label: "부품 수급" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 4, key: "kyosan_contact_report_sent", label: "교산 연락/보고서 발송" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 5, key: "waiting_kyosan_reply", label: "교산 회신 대기" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 6, key: "repair_or_defective_parts_replacement", label: "수리 또는 불량 부품 교체" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 7, key: "power_on_test", label: "전원 인가 테스트" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 8, key: "waiting_kyosan_shipment_approval", label: "교산 출하 승인 대기" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 9, key: "shipment_approved", label: "출하 승인" },
  { workflowType: "WARRANTY_TOTAL_CONTROLLER", order: 10, key: "shipment_completed", label: "출하 완료" },

  // Pending billing workflows deliberately stop at intake inspection.
  { workflowType: "PENDING_MATCHER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "PENDING_MATCHER", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "PENDING_GENERATOR", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "PENDING_GENERATOR", order: 2, key: "intake_inspection", label: "인수점검" },
  { workflowType: "PENDING_TOTAL_CONTROLLER", order: 1, key: "product_intake", label: "제품 인수" },
  { workflowType: "PENDING_TOTAL_CONTROLLER", order: 2, key: "intake_inspection", label: "인수점검" },
];

/**
 * billingType은 아래 백필 규칙으로 mockRepairCases 내보내기 시 한 번만
 * 채워 넣는다(실제 DB migration 0021의 백필 규칙과 동일 — PAID_GENERATOR
 * -> PAID, WARRANTY_GENERATOR -> WARRANTY, MATCHER -> null/추측하지 않음).
 * 이 데모 픽스처는 "이미 존재하는 과거 데이터"를 흉내 내는 것이지,
 * workflowType으로부터 실시간으로 유도하는 로직이 아니다 — 신규 접수는
 * 항상 사용자가 직접 고른 실제 billingType 값을 갖는다
 * (submit-intake.ts/repair-case-input.ts 참고).
 */
const mockRepairCasesRaw: Omit<RepairCase, "billingType">[] = [
  {
    id: "rc-001",
    intakeNumber: "D260601",
    customerId: "c-001",
    endUserId: "eu-001",
    productId: "p-001",
    workflowType: "MATCHER",
    status: "SHIPMENT_COMPLETED",
    priority: "NORMAL",
    assignedEngineerId: "u-004",
    receivedAt: "2026-06-01",
    customerRequestedDueDate: "2026-06-25",
    internalTargetShipmentDate: "2026-06-22",
    actualShipmentDate: "2026-06-24",
    isLocked: true,
    createdAt: "2026-06-01T01:00:00.000Z",
    reportedSymptom: "전원 인가 시 출력이 불안정하다는 신고",
    intakeInspectionResult: "외관 및 기본 동작 점검 결과 특이사항 없음",
    currentDiagnosisSummary: "부품 교체 후 정상 동작 확인 완료",
    nextPlannedAction: "출하 완료로 추가 조치 없음",
    exceptionStatus: null,
    currentWorkflowStepKey: "shipment_completed",
  },
  {
    id: "rc-002",
    intakeNumber: "D260602",
    customerId: "c-002",
    endUserId: "eu-003",
    productId: "p-003",
    workflowType: "PAID_GENERATOR",
    status: "SHIPMENT_COMPLETED",
    priority: "LOW",
    assignedEngineerId: "u-005",
    receivedAt: "2026-06-03",
    customerRequestedDueDate: "2026-06-30",
    internalTargetShipmentDate: "2026-06-27",
    actualShipmentDate: "2026-06-29",
    isLocked: true,
    createdAt: "2026-06-03T01:00:00.000Z",
    reportedSymptom: "측정값이 기준치보다 낮게 나온다는 신고",
    intakeInspectionResult: "내부 부품 노후로 인한 성능 저하 확인",
    currentDiagnosisSummary: "불량 부품 교체 후 정상 범위 확인",
    nextPlannedAction: "출하 완료로 추가 조치 없음",
    exceptionStatus: null,
    currentWorkflowStepKey: "shipment_completed",
  },
  {
    id: "rc-003",
    intakeNumber: "D260603",
    customerId: "c-003",
    endUserId: "eu-004",
    productId: "p-005",
    workflowType: "WARRANTY_GENERATOR",
    status: "SHIPMENT_COMPLETED",
    priority: "NORMAL",
    assignedEngineerId: "u-006",
    receivedAt: "2026-06-10",
    customerRequestedDueDate: "2026-07-01",
    internalTargetShipmentDate: "2026-06-29",
    // 고객사 승인 지연으로 실제 출하가 목표일보다 늦어진 데모 사례.
    // DEMO_REFERENCE_DATE(2026-08)와 같은 달에 출하 완료되어 "금월 출하 완료"
    // 카드/월별 필터를 검증할 수 있는 유일한 사례로 의도적으로 선택했다.
    actualShipmentDate: "2026-08-02",
    isLocked: true,
    createdAt: "2026-06-10T01:00:00.000Z",
    reportedSymptom: "사용 중 자동 전원 종료 현상 신고",
    intakeInspectionResult: "보증 기간 내 결함으로 확인",
    currentDiagnosisSummary: "무상 수리 완료, 정상 동작 확인",
    nextPlannedAction: "출하 완료로 추가 조치 없음",
    exceptionStatus: null,
    currentWorkflowStepKey: "shipment_completed",
  },
  {
    id: "rc-004",
    intakeNumber: "D260701",
    customerId: "c-004",
    endUserId: "eu-005",
    productId: "p-007",
    workflowType: "MATCHER",
    status: "WAITING_SHIPMENT",
    priority: "HIGH",
    assignedEngineerId: "u-004",
    receivedAt: "2026-07-02",
    customerRequestedDueDate: "2026-08-06",
    // DEMO_REFERENCE_DATE(2026-08-04)보다 하루 뒤로 잡아, 의도치 않게
    // 세 번째 지연 사례가 되지 않도록 한다(지연 데모는 rc-007/rc-009 두 건만).
    internalTargetShipmentDate: "2026-08-05",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-07-02T01:00:00.000Z",
    reportedSymptom: "화면 표시부 일부 깜빡임 신고",
    intakeInspectionResult: "표시부 연결 불량 확인",
    currentDiagnosisSummary: "수리 및 테스트 완료, 출하 대기 중",
    nextPlannedAction: "출하 절차 진행 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "waiting_shipment",
  },
  {
    id: "rc-005",
    intakeNumber: "D260702",
    customerId: "c-005",
    endUserId: "eu-006",
    productId: "p-002",
    workflowType: "PAID_GENERATOR",
    status: "WAITING_SHIPMENT_APPROVAL",
    priority: "NORMAL",
    assignedEngineerId: "u-005",
    receivedAt: "2026-07-05",
    customerRequestedDueDate: "2026-08-10",
    internalTargetShipmentDate: "2026-08-07",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-07-05T01:00:00.000Z",
    reportedSymptom: "출력 세기 저하 신고",
    intakeInspectionResult: "내부 회로 손상 확인",
    currentDiagnosisSummary: "수리 완료, 교산 출하 승인 대기 중",
    nextPlannedAction: "교산 승인 회신 대기",
    exceptionStatus: null,
    currentWorkflowStepKey: "waiting_kyosan_shipment_approval",
  },
  {
    id: "rc-006",
    intakeNumber: "D260703",
    customerId: "c-006",
    endUserId: "eu-007",
    productId: "p-004",
    workflowType: "WARRANTY_GENERATOR",
    status: "IN_REPAIR",
    priority: "URGENT",
    assignedEngineerId: "u-006",
    receivedAt: "2026-07-08",
    customerRequestedDueDate: "2026-08-01",
    internalTargetShipmentDate: "2026-08-06",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-07-08T01:00:00.000Z",
    reportedSymptom: "간헐적 재시작 현상 신고",
    intakeInspectionResult: "원인 특정을 위한 추가 점검 필요 확인",
    currentDiagnosisSummary: "부품 수급 완료, 보류 상태로 수리 일시 중단",
    nextPlannedAction: "보류 사유 해소 후 수리 재개 예정",
    // 워크플로 진행(수리 중)과 별개로 예외 상태가 동시에 붙는 데모 사례.
    exceptionStatus: "ON_HOLD",
    currentWorkflowStepKey: "repair_or_defective_parts_replacement",
  },
  {
    id: "rc-007",
    intakeNumber: "D260704",
    customerId: "c-007",
    endUserId: "eu-008",
    productId: "p-006",
    workflowType: "MATCHER",
    status: "IN_REPAIR",
    priority: "HIGH",
    assignedEngineerId: "u-004",
    receivedAt: "2026-07-10",
    customerRequestedDueDate: "2026-07-28",
    // 오늘(2026-08-04) 기준으로 지난 목표 출하일 → isRepairCaseOverdue()가 true를 반환하는 데모 사례
    internalTargetShipmentDate: "2026-07-30",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-07-10T01:00:00.000Z",
    reportedSymptom: "소음 발생 신고",
    intakeInspectionResult: "내부 팬 이상 확인",
    currentDiagnosisSummary: "부품 수급 완료, 수리 진행 중",
    nextPlannedAction: "수리 완료 후 테스트 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "repair_in_progress",
  },
  {
    id: "rc-008",
    intakeNumber: "D260705",
    customerId: "c-001",
    endUserId: "eu-002",
    productId: "p-008",
    workflowType: "PAID_GENERATOR",
    status: "WAITING_PARTS_SUPPLY",
    priority: "NORMAL",
    assignedEngineerId: "u-005",
    receivedAt: "2026-07-14",
    customerRequestedDueDate: "2026-08-12",
    internalTargetShipmentDate: "2026-08-09",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-07-14T01:00:00.000Z",
    reportedSymptom: "기능 일부 미동작 신고",
    intakeInspectionResult: "필요 부품 확인 완료",
    currentDiagnosisSummary: "부품 수급 대기 중",
    nextPlannedAction: "부품 입고 후 수리 착수 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "parts_supply",
  },
  {
    id: "rc-009",
    intakeNumber: "D260706",
    customerId: "c-002",
    endUserId: "eu-009",
    productId: "p-009",
    workflowType: "WARRANTY_GENERATOR",
    status: "WAITING_PARTS_SUPPLY",
    priority: "HIGH",
    assignedEngineerId: "u-006",
    receivedAt: "2026-07-18",
    customerRequestedDueDate: "2026-07-31",
    // 두 번째 지연 데모 사례
    internalTargetShipmentDate: "2026-08-01",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-07-18T01:00:00.000Z",
    reportedSymptom: "측정 오차 발생 신고",
    intakeInspectionResult: "핵심 부품 결함 확인",
    currentDiagnosisSummary: "해외 부품 수급 지연으로 대기 중",
    nextPlannedAction: "부품 입고 확인 후 수리 재개 예정",
    // 워크플로 상태(부품 수급 대기)와 예외 상태(부품 대기)가 동시에 표시되는 데모 사례.
    exceptionStatus: "PARTS_WAITING",
    currentWorkflowStepKey: "parts_supply",
  },
  {
    id: "rc-010",
    intakeNumber: "D260801",
    customerId: "c-003",
    endUserId: null,
    productId: "p-001",
    workflowType: "MATCHER",
    status: "WAITING_INTAKE_INSPECTION",
    priority: "NORMAL",
    assignedEngineerId: null,
    receivedAt: "2026-08-01",
    customerRequestedDueDate: "2026-08-25",
    internalTargetShipmentDate: "2026-08-22",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-01T01:00:00.000Z",
    reportedSymptom: "전원이 켜지지 않는다는 신고",
    intakeInspectionResult: null,
    currentDiagnosisSummary: null,
    nextPlannedAction: "인수점검 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "intake_inspection",
  },
  {
    id: "rc-011",
    intakeNumber: "D260802",
    customerId: "c-004",
    endUserId: "eu-005",
    productId: "p-003",
    workflowType: "PAID_GENERATOR",
    status: "WAITING_INTAKE_INSPECTION",
    priority: "LOW",
    assignedEngineerId: null,
    receivedAt: "2026-08-02",
    customerRequestedDueDate: "2026-08-28",
    internalTargetShipmentDate: "2026-08-25",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-02T01:00:00.000Z",
    reportedSymptom: "이상 동작음 발생 신고",
    intakeInspectionResult: null,
    currentDiagnosisSummary: null,
    nextPlannedAction: "인수점검 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "intake_inspection",
  },
  {
    id: "rc-012",
    intakeNumber: "D260803",
    customerId: "c-005",
    endUserId: "eu-006",
    productId: "p-005",
    workflowType: "WARRANTY_GENERATOR",
    status: "WAITING_KYOSAN_REPLY",
    priority: "NORMAL",
    assignedEngineerId: "u-004",
    receivedAt: "2026-08-02",
    customerRequestedDueDate: "2026-08-20",
    internalTargetShipmentDate: "2026-08-18",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-02T01:00:00.000Z",
    reportedSymptom: "정밀도 저하 신고",
    intakeInspectionResult: "보증 대상 여부 확인 중",
    currentDiagnosisSummary: "교산 측 응답 대기 중",
    nextPlannedAction: "교산 응답 수신 후 처리 방향 결정",
    exceptionStatus: "WAITING_KYOSAN_RESPONSE",
    currentWorkflowStepKey: "waiting_kyosan_reply",
  },
  {
    id: "rc-013",
    intakeNumber: "D260804",
    customerId: "c-006",
    endUserId: "eu-007",
    productId: "p-007",
    workflowType: "MATCHER",
    status: "WAITING_KYOSAN_REPLY",
    priority: "HIGH",
    assignedEngineerId: "u-005",
    receivedAt: "2026-08-03",
    customerRequestedDueDate: "2026-08-22",
    internalTargetShipmentDate: "2026-08-20",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-03T01:00:00.000Z",
    reportedSymptom: "반복적인 오작동 신고",
    intakeInspectionResult: "1차 점검 및 교산 문의 완료",
    currentDiagnosisSummary: "교산 후속 회신 대기 중",
    nextPlannedAction: "회신 수신 후 견적 작성 예정",
    exceptionStatus: null,
    // Matcher 워크플로의 두 번째 "교산 회신 대기"(order 8) 사례 — 첫 번째
    // occurrence(order 4, waiting_kyosan_reply)와 key가 다름을 보여주기 위해
    // 의도적으로 두 번째 key를 사용한다.
    currentWorkflowStepKey: "waiting_kyosan_reply_followup",
  },
  {
    id: "rc-014",
    intakeNumber: "D260805",
    customerId: "c-007",
    endUserId: "eu-008",
    productId: "p-002",
    workflowType: "PAID_GENERATOR",
    status: "WAITING_PO",
    priority: "NORMAL",
    assignedEngineerId: "u-006",
    receivedAt: "2026-08-03",
    customerRequestedDueDate: "2026-08-24",
    internalTargetShipmentDate: "2026-08-21",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-03T01:00:00.000Z",
    reportedSymptom: "출력 불안정 신고",
    intakeInspectionResult: "부품 교체 필요 확인",
    currentDiagnosisSummary: "견적 발송 완료, 고객 PO 대기 중",
    nextPlannedAction: "PO 접수 후 부품 수급 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "waiting_po",
  },
  {
    id: "rc-015",
    intakeNumber: "D260806",
    customerId: "c-001",
    endUserId: "eu-001",
    productId: "p-004",
    // 데이터 정합성 수정: 무상(보증) Generator 워크플로에는 PO 단계가 전혀
    // 없다(보증 수리는 유상이 아니므로 발주 절차가 없음). 기존
    // WARRANTY_GENERATOR + WAITING_PO 조합은 실제로 불가능한 상태였다.
    // Stage C-1에서 유상 Generator로 정정한다.
    workflowType: "PAID_GENERATOR",
    status: "WAITING_PO",
    priority: "LOW",
    assignedEngineerId: "u-004",
    receivedAt: "2026-08-03",
    customerRequestedDueDate: "2026-08-26",
    internalTargetShipmentDate: "2026-08-24",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-03T01:00:00.000Z",
    reportedSymptom: "화면 오류 표시 신고",
    intakeInspectionResult: "제어 보드 이상 확인",
    currentDiagnosisSummary: "견적 발송 완료, 고객 PO 대기 중",
    nextPlannedAction: "PO 접수 후 부품 수급 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "waiting_po",
  },
  {
    id: "rc-016",
    intakeNumber: "D260807",
    customerId: "c-002",
    endUserId: "eu-003",
    productId: "p-006",
    workflowType: "MATCHER",
    status: "IN_REPAIR",
    priority: "URGENT",
    assignedEngineerId: "u-005",
    receivedAt: "2026-08-04",
    customerRequestedDueDate: "2026-08-15",
    internalTargetShipmentDate: "2026-08-13",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-04T01:00:00.000Z",
    reportedSymptom: "긴급 고장 신고",
    intakeInspectionResult: "주요 부품 손상 확인",
    currentDiagnosisSummary: "긴급 수리 진행 중",
    nextPlannedAction: "수리 완료 후 테스트 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "repair_in_progress",
  },
  {
    id: "rc-017",
    intakeNumber: "D260808",
    customerId: "c-003",
    endUserId: "eu-004",
    productId: "p-008",
    workflowType: "PAID_GENERATOR",
    status: "WAITING_SHIPMENT_APPROVAL",
    priority: "NORMAL",
    assignedEngineerId: "u-006",
    receivedAt: "2026-08-04",
    customerRequestedDueDate: "2026-08-14",
    internalTargetShipmentDate: "2026-08-12",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-04T01:00:00.000Z",
    reportedSymptom: "성능 저하 신고",
    intakeInspectionResult: "부품 노후 확인",
    currentDiagnosisSummary: "수리 및 테스트 완료, 출하 승인 대기 중",
    nextPlannedAction: "교산 승인 회신 대기",
    exceptionStatus: null,
    currentWorkflowStepKey: "waiting_kyosan_shipment_approval",
  },
  {
    id: "rc-018",
    intakeNumber: "D260809",
    customerId: "c-004",
    endUserId: "eu-005",
    productId: "p-009",
    // 데이터 정합성 수정: 무상(보증) Generator 워크플로에는 "출하 대기"에
    // 해당하는 단계가 없다(출하 승인 이후 바로 출하 완료로 이어짐). 이
    // 단계는 Matcher 워크플로에만 존재하므로 Stage C-1에서 Matcher로
    // 정정한다.
    workflowType: "MATCHER",
    status: "WAITING_SHIPMENT",
    priority: "NORMAL",
    assignedEngineerId: "u-004",
    receivedAt: "2026-08-04",
    customerRequestedDueDate: "2026-08-16",
    internalTargetShipmentDate: "2026-08-14",
    actualShipmentDate: null,
    isLocked: false,
    createdAt: "2026-08-04T01:00:00.000Z",
    reportedSymptom: "연결 불량 신고",
    intakeInspectionResult: "커넥터 손상 확인",
    currentDiagnosisSummary: "출하 승인 완료, 출하 대기 중",
    nextPlannedAction: "출하 절차 진행 예정",
    exceptionStatus: null,
    currentWorkflowStepKey: "waiting_shipment",
  },
];

const BILLING_TYPE_BACKFILL: Record<RepairCase["workflowType"], RepairCase["billingType"]> = {
  MATCHER: null,
  PAID_MATCHER: "PAID",
  WARRANTY_MATCHER: "WARRANTY",
  PAID_GENERATOR: "PAID",
  WARRANTY_GENERATOR: "WARRANTY",
  PAID_TOTAL_CONTROLLER: "PAID",
  WARRANTY_TOTAL_CONTROLLER: "WARRANTY",
  PENDING_MATCHER: "PENDING_DECISION",
  PENDING_GENERATOR: "PENDING_DECISION",
  PENDING_TOTAL_CONTROLLER: "PENDING_DECISION",
};

export const mockRepairCases: RepairCase[] = mockRepairCasesRaw.map((c) => ({
  ...c,
  billingType: BILLING_TYPE_BACKFILL[c.workflowType],
}));

export const mockWorkHistories: WorkHistory[] = [
  { id: "wh-001", repairCaseId: "rc-001", engineerId: "u-004", workedAt: "2026-06-05T09:30:00+09:00", workType: "INSPECTION", description: "인수점검 완료, 이상 없음 확인", symptom: "전원 인가 시 출력 불안정", suspectedCause: "내부 부품 노후 추정", actionTaken: null, partsUsed: null, nextAction: "정밀 진단 및 부품 교체 검토", previousStatus: null, newStatus: null },
  { id: "wh-002", repairCaseId: "rc-001", engineerId: "u-004", workedAt: "2026-06-15T13:00:00+09:00", workType: "REPAIR", description: "부품 교체 후 전원 인가 테스트 통과", symptom: null, suspectedCause: null, actionTaken: "전원부 부품 교체", partsUsed: "전원부 안정화 모듈 1개", nextAction: "출하 절차 진행", previousStatus: null, newStatus: null },

  { id: "wh-003", repairCaseId: "rc-002", engineerId: "u-005", workedAt: "2026-06-06T10:00:00+09:00", workType: "INSPECTION", description: "인수점검 및 초기 진단 수행", symptom: "측정값 기준치 미달", suspectedCause: "내부 부품 노후 추정", actionTaken: null, partsUsed: null, nextAction: "불량 부품 확인 후 교체 예정", previousStatus: null, newStatus: null },
  { id: "wh-004", repairCaseId: "rc-002", engineerId: "u-005", workedAt: "2026-06-20T11:30:00+09:00", workType: "REPAIR", description: "불량 부품 교체 완료", symptom: null, suspectedCause: null, actionTaken: "불량 부품 교체", partsUsed: "측정 모듈 1개", nextAction: "출하 절차 진행", previousStatus: null, newStatus: null },

  { id: "wh-005", repairCaseId: "rc-003", engineerId: "u-006", workedAt: "2026-06-12T09:00:00+09:00", workType: "INSPECTION", description: "무상 보증 대상 확인, 인수점검 완료", symptom: "사용 중 자동 전원 종료", suspectedCause: "보증 기간 내 결함", actionTaken: null, partsUsed: null, nextAction: "무상 수리 진행", previousStatus: null, newStatus: null },
  { id: "wh-006", repairCaseId: "rc-003", engineerId: "u-006", workedAt: "2026-06-25T14:00:00+09:00", workType: "REPAIR", description: "수리 완료 및 전원 인가 테스트 통과", symptom: null, suspectedCause: null, actionTaken: "결함 부품 교체", partsUsed: "전원 제어 모듈 1개", nextAction: "출하 절차 진행", previousStatus: null, newStatus: null },

  { id: "wh-007", repairCaseId: "rc-004", engineerId: "u-004", workedAt: "2026-07-03T09:30:00+09:00", workType: "INSPECTION", description: "인수점검 수행, 경미한 손상 확인", symptom: "화면 표시부 깜빡임", suspectedCause: "표시부 연결 불량 추정", actionTaken: null, partsUsed: null, nextAction: "연결부 수리 예정", previousStatus: null, newStatus: null },
  { id: "wh-008", repairCaseId: "rc-004", engineerId: "u-004", workedAt: "2026-07-20T15:00:00+09:00", workType: "REPAIR", description: "수리 및 전원 인가 테스트 완료, 출하 대기", symptom: null, suspectedCause: null, actionTaken: "표시부 연결 케이블 교체", partsUsed: "연결 케이블 1개", nextAction: "출하 절차 진행", previousStatus: null, newStatus: null },

  { id: "wh-009", repairCaseId: "rc-005", engineerId: "u-005", workedAt: "2026-07-06T09:00:00+09:00", workType: "INSPECTION", description: "인수점검 완료", symptom: "출력 세기 저하", suspectedCause: "내부 회로 손상 추정", actionTaken: null, partsUsed: null, nextAction: "회로 수리 예정", previousStatus: null, newStatus: null },
  {
    id: "wh-010",
    repairCaseId: "rc-005",
    engineerId: "u-005",
    workedAt: "2026-07-25T16:00:00+09:00",
    workType: "STATUS_CHANGE",
    description: "수리 완료, 교산 출하 승인 대기 상태로 전환",
    symptom: null,
    suspectedCause: null,
    actionTaken: "손상 회로 수리 완료",
    partsUsed: "회로 기판 1개",
    nextAction: "교산 승인 회신 대기",
    previousStatus: "IN_REPAIR",
    newStatus: "WAITING_SHIPMENT_APPROVAL",
  },

  { id: "wh-011", repairCaseId: "rc-006", engineerId: "u-006", workedAt: "2026-07-09T09:00:00+09:00", workType: "INSPECTION", description: "인수점검 및 부품 수급 요청", symptom: "간헐적 재시작 현상", suspectedCause: "원인 특정을 위한 추가 점검 필요", actionTaken: null, partsUsed: null, nextAction: "부품 수급 요청", previousStatus: null, newStatus: null },
  { id: "wh-012", repairCaseId: "rc-006", engineerId: "u-006", workedAt: "2026-08-01T10:30:00+09:00", workType: "REPAIR", description: "부품 수급 완료, 수리 진행 중(보류 상태)", symptom: null, suspectedCause: null, actionTaken: "수급된 부품으로 교체 착수", partsUsed: "제어 보드 1개", nextAction: "보류 사유 해소 후 수리 재개", previousStatus: null, newStatus: null },

  { id: "wh-013", repairCaseId: "rc-007", engineerId: "u-004", workedAt: "2026-07-11T09:00:00+09:00", workType: "INSPECTION", description: "인수점검 완료, 부품 수급 대기", symptom: "소음 발생", suspectedCause: "내부 팬 이상 추정", actionTaken: null, partsUsed: null, nextAction: "부품 수급 대기", previousStatus: null, newStatus: null },
  { id: "wh-014", repairCaseId: "rc-007", engineerId: "u-004", workedAt: "2026-07-29T11:00:00+09:00", workType: "REPAIR", description: "부품 수급 완료, 수리 착수", symptom: null, suspectedCause: null, actionTaken: "냉각팬 교체 착수", partsUsed: "냉각팬 1개", nextAction: "수리 완료 후 테스트 예정", previousStatus: null, newStatus: null },

  { id: "wh-015", repairCaseId: "rc-008", engineerId: "u-005", workedAt: "2026-07-15T09:30:00+09:00", workType: "INSPECTION", description: "인수점검 완료, 필요 부품 확인", symptom: "기능 일부 미동작", suspectedCause: "구동부 부품 결함 추정", actionTaken: null, partsUsed: null, nextAction: "부품 입고 후 수리 착수 예정", previousStatus: null, newStatus: null },

  { id: "wh-016", repairCaseId: "rc-009", engineerId: "u-006", workedAt: "2026-07-19T09:00:00+09:00", workType: "INSPECTION", description: "인수점검 완료, 해외 부품 수급 요청", symptom: "측정 오차 발생", suspectedCause: "핵심 부품 결함 확인", actionTaken: null, partsUsed: null, nextAction: "해외 부품 입고 대기", previousStatus: null, newStatus: null },

  { id: "wh-017", repairCaseId: "rc-012", engineerId: "u-004", workedAt: "2026-08-02T09:30:00+09:00", workType: "INSPECTION", description: "인수점검 완료, 교산 측 회신 대기 중", symptom: "정밀도 저하", suspectedCause: "보증 대상 여부 확인 필요", actionTaken: null, partsUsed: null, nextAction: "교산 응답 대기", previousStatus: null, newStatus: null },

  { id: "wh-018", repairCaseId: "rc-013", engineerId: "u-005", workedAt: "2026-08-03T10:00:00+09:00", workType: "COMMUNICATION", description: "인수점검 완료, 교산 연락 및 보고서 발송", symptom: "반복적인 오작동", suspectedCause: null, actionTaken: "교산에 점검 보고서 발송", partsUsed: null, nextAction: "교산 후속 회신 대기", previousStatus: null, newStatus: null },

  {
    id: "wh-019",
    repairCaseId: "rc-014",
    engineerId: "u-006",
    workedAt: "2026-08-03T14:00:00+09:00",
    workType: "STATUS_CHANGE",
    description: "견적 발송 완료, 고객 PO 대기 상태로 전환",
    symptom: null,
    suspectedCause: null,
    actionTaken: "고객에게 견적서 발송",
    partsUsed: null,
    nextAction: "PO 접수 대기",
    previousStatus: "WAITING_KYOSAN_REPLY",
    newStatus: "WAITING_PO",
  },
  {
    id: "wh-020",
    repairCaseId: "rc-015",
    engineerId: "u-004",
    workedAt: "2026-08-03T14:30:00+09:00",
    workType: "STATUS_CHANGE",
    description: "견적 발송 완료, 고객 PO 대기 상태로 전환",
    symptom: null,
    suspectedCause: null,
    actionTaken: "고객에게 견적서 발송",
    partsUsed: null,
    nextAction: "PO 접수 대기",
    previousStatus: "WAITING_KYOSAN_REPLY",
    newStatus: "WAITING_PO",
  },

  { id: "wh-021", repairCaseId: "rc-016", engineerId: "u-005", workedAt: "2026-08-04T09:00:00+09:00", workType: "INSPECTION", description: "인수점검 완료, 긴급 수리 착수", symptom: "긴급 고장", suspectedCause: "주요 부품 손상", actionTaken: "긴급 수리 착수", partsUsed: null, nextAction: "수리 완료 후 테스트 예정", previousStatus: null, newStatus: null },

  {
    id: "wh-022",
    repairCaseId: "rc-017",
    engineerId: "u-006",
    workedAt: "2026-08-04T11:00:00+09:00",
    workType: "STATUS_CHANGE",
    description: "수리 및 전원 인가 테스트 완료, 출하 승인 대기 상태로 전환",
    symptom: null,
    suspectedCause: null,
    actionTaken: "부품 교체 및 전원 인가 테스트 완료",
    partsUsed: "구동 모듈 1개",
    nextAction: "교산 승인 회신 대기",
    previousStatus: "IN_REPAIR",
    newStatus: "WAITING_SHIPMENT_APPROVAL",
  },
  {
    id: "wh-023",
    repairCaseId: "rc-018",
    engineerId: "u-004",
    workedAt: "2026-08-04T15:00:00+09:00",
    workType: "STATUS_CHANGE",
    description: "출하 승인 완료, 출하 대기 상태로 전환",
    symptom: null,
    suspectedCause: null,
    actionTaken: "출하 승인 처리",
    partsUsed: null,
    nextAction: "출하 절차 진행",
    previousStatus: "WAITING_SHIPMENT_APPROVAL",
    newStatus: "WAITING_SHIPMENT",
  },
];

export const mockAttachments: AttachmentMetadata[] = [
  { id: "att-001", repairCaseId: "rc-001", uploadedBy: "u-004", fileName: "demo-photo-01.jpg", mimeType: "image/jpeg", fileSizeBytes: 2_048_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-06-05T02:00:00.000Z" },
  { id: "att-002", repairCaseId: "rc-001", uploadedBy: "u-004", fileName: "demo-report-01.pdf", mimeType: "application/pdf", fileSizeBytes: 512_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-06-16T02:00:00.000Z" },
  { id: "att-003", repairCaseId: "rc-002", uploadedBy: "u-005", fileName: "demo-photo-02.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_875_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-06-06T02:00:00.000Z" },
  { id: "att-004", repairCaseId: "rc-003", uploadedBy: "u-006", fileName: "demo-photo-03.jpg", mimeType: "image/jpeg", fileSizeBytes: 2_240_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-06-12T02:00:00.000Z" },
  { id: "att-005", repairCaseId: "rc-003", uploadedBy: "u-006", fileName: "demo-report-02.pdf", mimeType: "application/pdf", fileSizeBytes: 498_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-06-26T02:00:00.000Z" },
  { id: "att-006", repairCaseId: "rc-004", uploadedBy: "u-004", fileName: "demo-photo-04.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_980_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-07-03T02:00:00.000Z" },
  { id: "att-007", repairCaseId: "rc-005", uploadedBy: "u-005", fileName: "demo-photo-05.jpg", mimeType: "image/jpeg", fileSizeBytes: 2_105_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-07-06T02:00:00.000Z" },
  { id: "att-008", repairCaseId: "rc-006", uploadedBy: "u-006", fileName: "demo-photo-06.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_760_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-07-09T02:00:00.000Z" },
  { id: "att-009", repairCaseId: "rc-007", uploadedBy: "u-004", fileName: "demo-photo-07.jpg", mimeType: "image/jpeg", fileSizeBytes: 2_310_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-07-11T02:00:00.000Z" },
  { id: "att-010", repairCaseId: "rc-008", uploadedBy: "u-005", fileName: "demo-photo-08.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_690_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-07-15T02:00:00.000Z" },
  { id: "att-011", repairCaseId: "rc-009", uploadedBy: "u-006", fileName: "demo-photo-09.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_820_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-07-19T02:00:00.000Z" },
  { id: "att-012", repairCaseId: "rc-010", uploadedBy: "u-010", fileName: "demo-photo-10.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_540_000, malwareScanStatus: "PENDING", uploadedAt: "2026-08-01T02:00:00.000Z" },
  { id: "att-013", repairCaseId: "rc-011", uploadedBy: "u-010", fileName: "demo-photo-11.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_610_000, malwareScanStatus: "PENDING", uploadedAt: "2026-08-02T02:00:00.000Z" },
  { id: "att-014", repairCaseId: "rc-012", uploadedBy: "u-004", fileName: "demo-photo-12.jpg", mimeType: "image/jpeg", fileSizeBytes: 1_990_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-02T02:00:00.000Z" },
  { id: "att-015", repairCaseId: "rc-013", uploadedBy: "u-005", fileName: "demo-photo-13.jpg", mimeType: "image/jpeg", fileSizeBytes: 2_015_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-03T02:00:00.000Z" },
  { id: "att-016", repairCaseId: "rc-014", uploadedBy: "u-006", fileName: "demo-quote-01.pdf", mimeType: "application/pdf", fileSizeBytes: 305_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-03T02:00:00.000Z" },
  { id: "att-017", repairCaseId: "rc-015", uploadedBy: "u-004", fileName: "demo-quote-02.pdf", mimeType: "application/pdf", fileSizeBytes: 298_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-03T02:00:00.000Z" },
  { id: "att-018", repairCaseId: "rc-016", uploadedBy: "u-005", fileName: "demo-photo-14.jpg", mimeType: "image/jpeg", fileSizeBytes: 2_200_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-04T02:00:00.000Z" },
  { id: "att-019", repairCaseId: "rc-017", uploadedBy: "u-006", fileName: "demo-report-03.pdf", mimeType: "application/pdf", fileSizeBytes: 511_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-04T02:00:00.000Z" },
  { id: "att-020", repairCaseId: "rc-018", uploadedBy: "u-004", fileName: "demo-report-04.pdf", mimeType: "application/pdf", fileSizeBytes: 487_000, malwareScanStatus: "CLEAN", uploadedAt: "2026-08-04T02:00:00.000Z" },
];
